### ISSUE TITLE
you can add how to install lamp on ubuntu (Tukish language) (güzel ama ingiliççe)

### ISSUE THREAD

**Issue by OkancanCosar** [oguzhantasci/php_notes#1]
#### 1. MySQL kurulumu

<code>apt-get install mysql-server mysql-client</code>

ya da

<code>aptitude install mysql-server mysql-client</code>

Kurulum sırasında Mysql için root parolası istenecektir. Bu, Mysql için belirlenecek olan root parolasıdır.

New password for the MySQL “root” user: root      kullanıcı için yeni parolanız.

Repeat password for the MySQL “root” user: root      kullanıcı için tekrar parolanızı tekrar giriniz.

İki defa parola girildikten sonra eğer her şey yolunda gitmişse yapılandırma tamamlanacak, Mysql servisi başlatılacaktır.

#### 2. Apache2 kurulumu

<code>apt-get install apache2</code>

ya da

<code>aptitude install apache2</code>

Kurulum bitince Firefox’u açıp adres satırına http://localhost yazıldığında, tarayıcıya “It works!” başlıklı metin geldiyse kurulum sorunsuz tamamlanmış demektir.

Sayfanın üzerinde “It works!” yazdığına dikkat ediniz.

Eğer bu metin görünmüyorsa:

<code>/etc/init.d/apache2 start</code>

koduyla Apache çalıştırılmaya zorlanabilir, hata yakalanmaya çalışılabilir.

#### 3. PHP5 kurulumu

<code>apt-get install php5 libapache2-mod-php5</code>

ya da

<code>aptitude install php5 libapache2-mod-php5</code>

Kurulum bittikten sonra Apache’yi yeniden başlatmak gerekmektedir.

<code>/etc/init.d/apache2 restart</code>

PHP5 kurulumunu test etmek

phpinfo ile kurulumu ve PHP bilgilerini test etmek mümkündür.

<code>gedit /var/www/html/info.php</code>

komutuyla ilgili dizinde boş bir php dosyası açarak, içine aşağıdaki kodu:

<code><?php
    phpinfo();
    ?></code>

yapıştırıp, dosyayı kaydedip kapatmalıdır. Ardından Firefox adres satırına http://localhost/info.php yazıldığında, tarayıcı penceresine PHP bilgileri dökülecektir.

#### 4. PHP5 için MySQL desteği

PHP5′e MySQL desteği kazandırmak için, php5-mysql paketini yükleyebilirsiniz. Bir de uygulamalarınızın ihtiyaç duyacağı kimi PHP5 modüllerini yüklemek iyi bir fikirdir. Bu tür PHP5 modülleri için arama yapabilirsiniz:

<code>apt-cache search php5</code>

Şimdi yüklemek için şu kodu verin:

<code>apt-get install php5-mysql php5-curl php5-gd php5-intl php-pear php5-imagick php5-imap php5-mcrypt php5-memcache php5-ming php5-ps php5-pspell php5-recode php5-snmp php5-sqlite php5-tidy php5-xmlrpc php5-xsl</code>

Böylece PHP5, MySQL desteği kazanmış olur. Kurulum sonrasında Apache’yi tekrar başlatmak gerekir:

<code>service apache2 restart

Sonra tekrar Firefox ile http://localhost/info.php sayfasına gidildiğinde sayfanın altında MySQL’e ait bilgiler görebilir.

#### 5. PhpMyAdmin kurulumu: 
phpMyAdmin aracılığıyla MySQL veritabanlarını yönetebilirsiniz. Onu yüklemek iyi bir fikirdir:

<code>apt-get install phpmyadmin</code>

ya da

<code>aptitude install phpmyadmin</code>

Kurulum sırasında: “Web server to reconfigure automatically” biçiminde bir seçim yapılması istenecektir, burada “apache2” seçilmelidir; sonra “Configure database for phpmyadmin with dbconfig-common?” diye bir soru gelecektir buna da “Hayır” diye cevap verilmesi gerekiyor. Eğer yanlışlıkla evet denilirse, düzeltmek için:

<code>sudo gedit /etc/apache2/apache2.conf</code>

koduyla ilgili dosya açılır ve içine:

Alıntı

<code>Include /etc/phpmyadmin/apache.conf</code>

satırı eklenir. Apache tekrar başlatılır:

<code>sudo /etc/init.d/apache2 restart</code>

Sonra http://localhost/phpmyadmin ile işlem tekrar edilir. Gelen sayfada kullanıcı adı olarak root yazılır, parola olarak da MySQL kurulumunda belirlenen root parolası girilir.

#### /var/www/ dizininde rahat çalışmak üzere dosya izinlerinin ayarlanması gerekebilir:

<code>chmod -R 777 /var/www/</code>

kodu /www klasörüne ve alt dizinlerine yazma izni verecektir.

**Comment by oguzhantasci** [comment]
teşekkür ederim :smile: ayrı ayrı kurmak yerine xampp kurulumu gerçekleştirdim. linux-ubuntu 14.04 'de yapmamız gereken tek şey chmod ile yethi verip ./xampp.run dosyasını çalıştırmak oldu. Ayrıntılı bilgiye buradan ulaşabilirsin. https://www.apachefriends.org/tr/download.html

Eğer bu issue'yu pull request olarak atarsan repoya eklemek isterim. 

Teşekkürler :smiley:
