### ISSUE TITLE
redundancies

### ISSUE THREAD

**Issue by ozgurince** [oguzhantasci/php_notes#3]
You added 3 'database_connection.php'. You can add one and call it every time

**Comment by OkancanCosar** [comment]
there are 3 different connection file. maybe for different situation

**Comment by oguzhantasci** [comment]
actually 3 connection is same but i follow one tutorial and db process is different videos. Therefor, i added 3 different connection. 

@ozgurince @OkancanCosar thank u for that. :smile:
